POST /comment/register/1
Content-Type: application/json
Host: localhost:9999

{
  "writerId": "semi",
  "content": "semi's comment"
}
###
PUT /comment/modify/1
Content-Type: application/json
Host: localhost:9999

{
  "content": "modify semi's comment"
}
###
DELETE /comment/1
Content-Type: application/json
Host: localhost:9999