POST /participant/register/member
Content-Type: application/json
Host: localhost:9999

{
  "accountId" : "semi",
  "projectNo" : 2
}

###

DELETE /participant/2/semi
Content-Type: application/json
Host: localhost:9999

###

GET /participant/3
Content-Type: application/json
Host: localhost:9999