POST /project/register/semi
Content-Type: application/json
Host: localhost:9999

{
  "name": "프로젝트 등록되면서 프로젝트 관리자 등록 확인",
  "explanation": "프로젝트 등록 확인을 위한 프로젝트"
}

###

PUT /project/2/modify
Content-Type: application/json
Host: localhost:9999

{
  "state": "활성",
  "name": "첫번째 프로젝트(수정)",
  "explanation": "프로젝트 등록 테스트를 위한 프로젝트를 수정"
}

###

DELETE /project/2
Content-Type: application/json
Host: localhost:9999

###

GET /project/2
Content-Type: application/json
Host: localhost:9999

###
GET /project/list/semi/활성
Content-Type: application/json
Host: localhost:9999
