POST /tag/register/1
Content-Type: application/json
Host: localhost:9999

{
  "name": "업무"
}
###
PUT /tag/1
Content-Type: application/json
Host: localhost:9999

{
  "name": "과제(수정)"
}
###
DELETE /tag/2
Content-Type: application/json
Host: localhost:9999
###
GET /tag/list/1
Content-Type: application/json
Host: localhost:9999