POST /task/register/3/semi
Content-Type: application/json
Host: localhost:9999

{
  "title" : "업무",
  "content" : "업무 내용"
}

###

PUT /task/modify/2
Content-Type: application/json
Host: localhost:9999

{
  "title" : "업무(수정)",
  "content" : "업무 내용(수정)"
}

###

DELETE /task/1
Content-Type: application/json
Host: localhost:9999